spring.application.name=RoomFlow
server.port=8084

spring.main.banner-mode=off

management.endpoints.web.exposure.include=health,info

management.endpoint.health.show-details=always

spring.datasource.url=jdbc:postgresql://localhost:5435/roomflow_db
spring.datasource.username=myuser
spring.datasource.password=fialka
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.flyway.enabled=true

jwt.secret=a7d2e8f1c3b5a9e8d7f6c3a1b9e8d5f3c2a1b9d8e7f6c3a2b1d9e8f7c6a5b4d3
jwt.expiration=3600000

springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=method